name: publish
on: [push]
jobs:
  karsajobs-be:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the karsajobs-be Docker image
        run: |
          docker build . --tag ghcr.io/arifsptra/karsajobs-be:latest
          docker run ghcr.io/arifsptra/karsajobs-be:latest
          docker push ghcr.io/arifsptra/karsajobs-be:latest
